### PR TITLE
Added warning about supported Ipython versions

### PR DESCRIPTION
**Pull request by drevicko**
Ipython Notebook 2.0 or greater is not supported - probably good for people to know about it before experimenting!

### CODE REVIEW

**Comment by maximsch2** [comment]
Merged, thanks! Would you say that IPython 1.0 is too old to be interesting btw? Maybe I should remove the package from Package Control to avoid confusion?

**Comment by drevicko** [comment]
I guess removing from Package Control makes sense, though it'd be a shame to have nothing there... At least the presence of this package will make people think about creating something like for newer ipythons (and hopefully the ipython communication protocols will be more stable in future versions...?). 

Hmm... I wonder how hard it would be to detect the ipython version at install and complain/abort if it's not 1... Probably not worth the bother though!

**Comment by maximsch2** [comment]
Honestly, updating to new version of Jupyter shouldn't be that hard - we are using code from IPython to parse notebooks (in external/nbformat folder), so that needs to be updated + ipy_connection.py will be updated with new URLs (for sure) and maybe small tweaks to message protocol (not sure how drastic those are). Maybe you want to take a stab at it?

**Comment by drevicko** [comment]
I'll keep it on my todo list. It'd be nice to have! Currently I'm pretty time poor, but perhaps later in the year? 

In case someone else stumbles here and wants to pitch in, [this issue](https://github.com/maximsch2/SublimeIPythonNotebook/issues/25) has some info on what needs to be done.

**Pull request merged**
